---
title: "DELETE ME 5 - 2024 RUGS Program Progress: Reviewing Grants and Empowering R Communities"
description: "Quick update on the 2024 R User Groups (RUGS) Program. The review of the first batch of grants is in progress, marking the beginning of the awarding phase."
author: "R Consortium"
date: "01/24/2024"
---

Quick update on the 2024 R User Groups (RUGS) Program. The review of the first batch of grants is in progress, marking the beginning of the awarding phase. But there’s still plenty of time for you to apply!

Interested in building up your own R User Group and creating a strong R community where you live? R Consortium would like to help!

## [Apply now!](https://r-consortium.org/all-projects/rugsprogram.html)

## 2024 RUGS Program Highlights:

-   User Group Grants: Support for enhancing user engagement and user-centric initiatives.
-   Conference Grants: For organizing or attending events aligned with R Consortium goals.
-   Special Projects Grants: For groundbreaking ideas needing an initial push.

For details and to apply, [visit here](https://r-consortium.org/all-projects/rugsprogram.html). Your participation is pivotal for the growth of the R language.

## R User Groups: Strengthening Global Connections

With 74 active groups and over 67,000 members, R communities are a melting pot of knowledge and innovation. Discover what other RUGS organizers are doing and how they have solved tough problems restarting in person meetings or finding good locations or communicating effectively with their community… on our blog. Many RUGS case studies are available.

## Key Dates:

Application Period: Open through September 30th, 2024, but don’t wait!

*Note: Grants are not for software development or technical projects. For those, consider the ISC Grant Program. Learn more here.*

Join us in building the worldwide R community. Apply now and be part of the journey!

## [Apply now!](https://r-consortium.org/all-projects/rugsprogram.html)
