---
title: Events
format:
  html:
    execute:
      echo: false
---

## Upcoming Events

```{r}
# Data frame with HTML links
df <- data.frame(
  Title = c(
    '<a href="https://eurobioc2026.bioconductor.org/" target="_blank" rel="noreferrer noopener">EuroBioC 2026</a>',
    '<a href="https://rr2026.sciencesconf.org/" target="_blank" rel="noreferrer noopener">Rencontres 2026</a>',
    '<a href="https://cascadiarconf.com/" target="_blank" rel="noreferrer noopener">Cascadia R Conference</a>',
    '<a href="https://user2026.r-project.org/" target="_blank" rel="noreferrer noopener">useR! 2026</a>',
    '<a href="https://latin-r.com/" target="_blank" rel="noreferrer noopener">LatinR</a>'
  ),
  dates = c(
    "June 3-5, 2026",
    "June 16-18, 2026",
    "June 26-27, 2026",
    "July 6-9, 2026",
    "Nov 11, 2026"
  ),
  location = c(
    "Turku, Finland",
    "Nantes, France",
    "Portland, OR, USA",
    "Warsaw, Poland",
    "Virtual"
  ),
  icon = c(
    "Conference",
    "Conference",
    "Conference",
    "Conference",
    "Conference"
  ),
  Type = c(
    "Conference",
    "Conference",
    "Conference",
    "Conference",
    "Conference"
  ),
  stringsAsFactors = FALSE
)

df <- df |>
  dplyr::filter(icon %in% c("Conference", "Webinar")) |>
  dplyr::mutate(
    icon = ifelse(icon == "Webinar", "chalkboard-user", "handshake")
  )

library(gt)

gt_table <- gt(df) %>%
  fmt_icon(columns = icon) %>%
  cols_label(
    Title = "Title",
    dates = "Dates",
    location = "Location",
    icon = "Type"
  )%>%
  tab_options(
    heading.background.color = "lightblue",
    column_labels.background.color = "lightblue",
    column_labels.font.weight = "bold",
    table.font.size = "14px",
    column_labels.font.size = "16px"
  ) %>%
  opt_horizontal_padding(scale = 3) %>%
  opt_vertical_padding(scale = 2) %>%
  cols_merge(
    columns = c(Type, icon),
    pattern = "{2}    {1}"
  ) %>%
  fmt_markdown(columns = Title)


gt_table
```

## Recently Completed Events and Webinars

```{r}
# Data frame with HTML links
df <- data.frame(
  Title = c(
    '<a href="https://r-consortium.org/webinars/make-your-first-r-open-source-project-contribution.html" target="_blank" rel="noreferrer noopener">Make your first R open source project contribution with git, forks, and PRs</a>',
    '<a href="https://rconsortium.github.io/Risk_website/" target="_blank" rel="noreferrer noopener">Risk 2026</a>',
    '<a href="https://r-consortium.org/webinars/scaling-up-data-analysis-in-r-with-arrow.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: Scaling up data analysis in R with Arrow</a>',
    '<a href="https://r-consortium.org/webinars/making-health-economic-models-shiny.html" target="_blank" rel="noreferrer noopener">Making Health Economic Models Shiny: Our experience helping companies transition from Excel to R & Shiny</a>',
    '<a href="https://rconsortium.github.io/RplusAI_website/" target="_blank" rel="noreferrer noopener">R+AI</a>',
    '<a href="https://rstats.ai/gov" target="_blank" rel="noreferrer noopener">Government Data Science & AI Conference</a>',
    '<a href="https://r-consortium.org/webinars/jnj-hybrid-sas-r-submission-story.html" target="_blank" rel="noreferrer noopener">J&J: A Hybrid SAS/R Submission Story</a>',
    '<a href="https://earl-conference.com/" target="_blank" rel="noreferrer noopener">EARL (Enterprise Applications of the R Language) Tech Conference (EARL2025)</a>',
    '<a href="https://r-consortium.org/webinars/how-to-use-pointblank-to-understand-validate-and-document-your-data.html" target="_blank" rel="noreferrer noopener">R/Medicine Webinar: How to use pointblank to understand, validate, and document your data</a>',
    '<a href="https://r-consortium.org/webinars/modular-interoperable-extensible-topological-data-analysis-in-r.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: Modular, interoperable, and extensible topological data analysis in R</a>',
    '<a href="https://shiny-in-production.jumpingrivers.com/" target="_blank" rel="noreferrer noopener">Shiny in Production</a>',
    '<a href="https://eurobioc2025.bioconductor.org/" target="_blank" rel="noreferrer noopener">European Bioconductor Conference (EuroBioC2025)</a>',
    '<a href="https://r-consortium.org/webinars/sas-to-r-in-pharma-creating-custom-solutions-for-closed-source-code.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: SAS to R in Pharma – Creating Custom Solutions for Closed-Source Code</a>',
    '<a href="https://dataconf.ai/nyc" target="_blank" rel="noreferrer noopener">New York Data Science & AI Conference</a>',
    '<a href="https://r-consortium.org/webinars/unlocking-collaborative-power-with-git-github-ci-cd-and-llms-in-pharma.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: Unlocking Collaborative Power with Git, GitHub CI/CD, and LLMs in Pharma</a>',
    '<a href="https://user2025.r-project.org/" target="_blank" rel="noreferrer noopener">useR! 2025</a>',
    '<a href="https://r-consortium.org/webinars/open-source-adoption-in-japans-pharma-industry.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: Open Source Software Adoption in Japan\'s Pharma Industry: Key Findings from the 2024 JPMA R Usage Survey</a>',
    '<a href="https://r-consortium.org/posts/teaching-r-to-investigative-journalists-in-brazil/" target="_blank" rel="noreferrer noopener">Brazilian Association of Investigative Journalism (Abraji)</a>',
    '<a href="https://www.psiweb.org/events/event-item/2025/07/03/default-calendar/one-day-event-change-management-for-moving-to-r-open-source" target="_blank" rel="noreferrer noopener">Change Management for Moving to R/Open Source</a>',
    '<a href="https://r-consortium.org/webinars/r-for-health-technology-assessment-identifying-needs-streamlining-processes-and-building-bridges.html" target="_blank" rel="noreferrer noopener">R Consortium Working Group Webinar: R for Health Technology Assessment (HTA): Identifying Needs, Streamlining Processes, and Building Bridges</a>',
    '<a href="https://r-consortium.org/webinars/from-paper-to-pixels-digitizing-water-quality-data-collection-with-posit-and-esri-integration.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: From Paper to Pixels: Digitizing Water Quality Data Collection with Posit and Esri Integration</a>',
    '<a href="https://r-consortium.org/webinars/scaling-the-r-spatial-ecosystem-for-the-modern-composable-data-pipeline.html" target="_blank" rel="noreferrer noopener">R Consortium Webinar: Scaling the r-spatial ecosystem for the modern composable data pipeline</a>',
    '<a href="https://gbcc2025.bioconductor.org/about/overview/" target="_blank" rel="noreferrer noopener">Galaxy and Bioconductor Community Conference 2025</a>',
    '<a href="https://cascadiarconf.com/" target="_blank" rel="noreferrer noopener">Cascadia R Conference</a>',
    '<a href="https://ghana-rusers.org/event/ghana-r-conference-2025/" target="_blank" rel="noreferrer noopener">Ghana R Conference 2025</a>',
    '<a href="https://rconsortium.github.io/RMedicine_website/" target="_blank" rel="noreferrer noopener">R/Medicine 2025</a>',
    '<a href="https://rr2025.sciencesconf.org/" target="_blank" rel="noreferrer noopener">Rencontres 2025</a>',
    'PharmaRUG 2025',
    '<a href="https://r-consortium.org/webinars/rix-reproducible-data-science-environments-with-nix.html" target="_blank" rel="noreferrer noopener">Rix: reproducible data science environments with Nix</a>',
    '<a href="https://r-consortium.org/webinars/quantification-of-participation-risk-using-r-and-rshiny.html" target="_blank" rel="noreferrer noopener">Quantification of Participation Risk using R and R Shiny</a>',
    '<a href="https://r-consortium.org/webinars/tidy-finance-webinar-series.html#value-companies-using-discounted-cash-flow-analysis" target="_blank" rel="noreferrer noopener">Value Companies using Discounted Cash Flow Analysis</a>',
    '<a href="https://latin-r.com/" target="_blank" rel="noreferrer noopener">LatinR 2024</a>',
    '<a href="https://r-consortium.org/webinars/containerization-and-r-for-reproducibility.html" target="_blank" rel="noreferrer noopener">R/Medicine Webinar: Containerization and R for Reproducibility and More</a>',
    '<a href="https://r-consortium.org/webinars/tidy-finance-webinar-series.html#analyze-companies-using-financial-ratios" target="_blank" rel="noreferrer noopener">Analyze Companies using Financial Ratios</a>',
    '<a href="https://www.rstats.ai/gov" target="_blank" rel="noreferrer noopener">2024 Government & Public Sector R Conference</a>',
    '<a href="https://rinpharma.com/" target="_blank" rel="noreferrer noopener">R/Pharma 2024 with new APAC Track</a>',
    '<a href="https://r-consortium.org/webinars/unlocking-insights-from-latinr.html" target="_blank" rel="noreferrer noopener">Unlocking Insights from LatinR: Collaboration and Innovation in Data Science</a>',
    '<a href="https://shiny-in-production.jumpingrivers.com/" target="_blank" rel="noreferrer noopener">Shiny in Production 2024</a>',
    '<a href="https://r-consortium.org/webinars/tidy-finance-webinar-series.html#evaluate-performance-using-the-capital-asset-pricing-model" target="_blank" rel="noreferrer noopener">Evaluate Performance using the Capital Asset Pricing Model</a>',
    '<a href="https://earl-conference.com/" target="_blank" rel="noreferrer noopener">EARL 2024</a>',
    '<a href="https://r-consortium.org/webinars/tidy-finance-webinar-series.html#optimize-portfolios-using-the-markowitz-model" target="_blank" rel="noreferrer noopener">Optimize Portfolios using the Markowitz Model</a>',
    '<a href="https://www.r-project.org/conferences/" target="_blank" rel="noreferrer noopener">useR! 2024</a>',
    '<a href="https://posit.co/conference/" target="_blank" rel="noreferrer noopener">posit::conf 2024</a>',
    '<a href="https://cascadiarconf.com/" target="_blank" rel="noreferrer noopener">Cascadia R Conference</a>',
    '<a href="https://www.rstats.nyc/" target="_blank" rel="noreferrer noopener">New York R Conference</a>',
    '<a href="https://www.rinfinance.com/" target="_blank" rel="noreferrer noopener">R/Finance 2024</a>',
    '<a href="https://satrday-london-2024.jumpingrivers.com/" target="_blank" rel="noreferrer noopener">SatRdays London 2024</a>',
    '<a href="https://www.r-consortium.org/webinars/r-medicine-quarto-for-reproducible-medical-manuscripts.html" target="_blank" rel="noreferrer noopener">R/Medicine: Quarto for Reproducible Medical Manuscripts</a>',
    '<a href="https://www.r-consortium.org/webinars/new-webinar-tidy-finance-and-accessing-financial-data.html" target="_blank" rel="noreferrer noopener">New Webinar: Tidy Finance and Accessing Financial Data</a>',
    '<a href="https://www.r-consortium.org/webinars/escape-the-data-dungeon.html" target="_blank" rel="noreferrer noopener">Escape the Data Dungeon: Unlock Scalable R Analytics and ML</a>',
    '<a href="https://www.r-consortium.org/webinars/from-vision-to-action-the-pfizer-r-center-of-excellence.html" target="_blank" rel="noreferrer noopener">From Vision to Action: The Pfizer R Center of Excellence-led journey to R Adoption</a>',
    '<a href="https://www.r-consortium.org/webinars/r-insurance-series.html#high-performance-programming-in-r" target="_blank" rel="noreferrer noopener">R/Insurance Series (4/4): High performance programming in R</a>',
    '<a href="https://www.r-consortium.org/webinars/visualizing-survival-data-with-the-ggsurvfit-r-package.html" target="_blank" rel="noreferrer noopener">Dan Sjoberg presenting on Plotting Survival with {ggsurvfit}</a>',
    '<a href="https://www.r-consortium.org/webinars/r-insurance-series.html#r-performance-culture" target="_blank" rel="noreferrer noopener">R/Insurance Series (3/4): R performance culture</a>',
    '<a href="https://www.r-consortium.org/webinars/r-insurance-series.html#from-programming-in-r-to-putting-r-into-production" target="_blank" rel="noreferrer noopener">R/Insurance Series (2/4): From programming in R to putting R into production</a>',
    '<a href="https://www.r-consortium.org/webinars/r-insurance-series.html#from-excel-to-programming-in-r" target="_blank" rel="noreferrer noopener">R/Insurance Series (1/4): From Excel to Programming in R</a>',
    '<a href="https://r-consortium.org/webinars/AdoptionOfRInJapansPharma.html" target="_blank" rel="noreferrer noopener">The use of R in Japan’s Pharma Industry</a>'
  ),
  dates = c(
    'Apr 8, 2026',
    'Feb 18-19, 2026',
    'Feb 10, 2026',
    'Nov 18, 2025',
    'Nov 12-13, 2025',
    'Oct 28-29, 2025',
    'Oct 21, 2025',
    'Oct 14-16, 2025',
    'Oct 16, 2025',
    'Oct 7, 2025',
    'Oct 7-8, 2025',
    'Sept 17-19, 2025',
    'Sept 9, 2025',
    'Aug 25-27, 2025',
    'Aug 28, 2025',
    'Aug 8-10, 2025',
    'July 23, 2025',
    'July 10-13, 2025',
    'July 3, 2025',
    'June 30, 2025',
    'June 27, 2025',
    'June 24, 2025',
    'June 23-26, 2025',
    'June 20-21, 2025',
    'June 19-20, 2025',
    'June 9-13, 2025',
    'May 19-21, 2025',
    'March 28, 2025',
    'March 13, 2025',
    'December 12, 2024',
    'December 4, 2024',
    'November 18-22, 2024',
    'November 19, 2024',
    'November 6, 2024',
    'October 29-30, 2024',
    'October 29-31, 2024',
    'October 22, 2024',
    'October 9-10, 2024',
    'October 9, 2024',
    'September 4-5, 2024',
    'September 4, 2024',
    'July 8-11, 2024',
    'August 12-14, 2024',
    'June 21-22, 2024',
    'May 16-17, 2024',
    'May 17-18, 2024',
    'April 27, 2024',
    'March 20, 2024',
    'March 6, 2024',
    'February 27, 2024',
    'February 8, 2024',
    'January 31, 2024',
    'January 25, 2024',
    'January 24, 2024',
    'January 17, 2024',
    'January 10, 2024',
    'January 8, 2024'
  ),
  location = c(
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Washington, D.C',
    'Virtual',
    'Brighton, UK',
    'Virtual',
    'Virtual',
    'Virtual',
    'Barcelona, Spain',
    'Virtual',
    'New York City, NY',
    'Virtual',
    'Durham, NC - Duke University',
    'Virtual',
    'São Paulo, Brazil',
    'Cambridge, UK',
    'Virtual',
    'Virtual',
    'Virtual',
    'Cold Spring Harbor Laboratory (CSHL), New York',
    'Portland, Oregon, USA',
    'Accra, Ghana',
    'Virtual',
    'Mons, Belgium',
    'Shanghai, Bejing',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Washington, DC, USA',
    'Virtual',
    'Virtual',
    'Newcastle upon Tyne, UK',
    'Virtual',
    'Brighton, UK',
    'Virtual',
    'Salzburg, Austria',
    'Seattle, WA, USA',
    'Seattle, WA, USA',
    'New York City, NY, USA',
    'Chicago, IL, USA',
    'London, UK',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual',
    'Virtual'
  ),
  Type = c(
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar'
  ),
  icon = c(
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Conference',
    'Webinar',
    'Webinar',
    'Conference',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Webinar',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Conference',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar',
    'Webinar'
  ),
  stringsAsFactors = FALSE
)

df <- df |>
  dplyr::filter(icon %in% c("Conference", "Webinar")) |>
  dplyr::mutate(
    icon = ifelse(icon == "Webinar", "chalkboard-user", "handshake")
  )

library(gt)

gt_table <- gt(df) %>%
  cols_label(
    Title = "Title",
    dates = "Dates",
    location = "Location",
    Type = "Type"
  ) %>%
  fmt_icon(columns = c(icon)) %>%
  cols_merge(
    columns = c(Type, icon),
    pattern = "{2}    {1}"
  ) %>%
  tab_options(
    heading.background.color = "grey",
    column_labels.background.color = "grey",
    column_labels.font.weight = "bold",
    table.font.size = "14px",
    column_labels.font.size = "16px"
  ) %>%
  opt_horizontal_padding(scale = 3) %>%
  opt_vertical_padding(scale = 2) %>%
  fmt_markdown(columns = c(Title))

gt_table

```
