---
title: "From Paper to Pixels: Digitizing Water Quality Data Collection with Posit and Esri Integration"
---

{{< video https://youtu.be/P3Mb1sBGRZY?feature=shared >}}

The Virginia Department of Environmental Quality (DEQ) is responsible for administering laws and regulations associated with air quality, water quality and supply, renewable energy, and land protection in the Commonwealth of Virginia. These responsibilities generate tremendous quantities of data from monitoring environmental quality, managing permitting processes across environmental media, responding to pollution events, and more. The data collected by DEQ requires management and analysis to gain insight, inform decision making, and meet legal and public obligations.

In this webinar, we will focus on the integration of our Posit and Esri environments to modernize data collection methods for water quality monitoring. We'll begin with a review of historic water quality data collection processes. Then, we’ll present the architecture of these environments and describe how they were leveraged to modernize mobile data collection at DEQ.

## Speakers 

* Joe Famularo - Analytics System Administrator
* Maddie Moore - GIS System Administrator
* Emma Jones - Water Monitoring Supervisor
* Scott Hasinger - Water Monitoring Supervisor