---
format:
  html:
    execute:
    echo: false
---

# Why Join the R Consortium?

The R Consortium is the mechanism for corporate entities and other organizations to support  and engage with the R Community. Membership in the R Consortium signals community leadership, a long term viewpoint, and an appreciation for the efforts of R’s open source contributors. Membership shows commitment and a desire to contribute to the community, strengthening it for the benefit of all.

## Membership in the R Consortium

-   Helps fund key R infrastructure such as the R-Hub build system, database interfaces, distributed computing architecture, regional conferences, local R user groups and more.
-   Provides a way for companies to generate industry-wide support for projects that they see as valuable.
    -   The bulk of the R Consortium budget goes directly to funding key community projects.
-   Through participation in the R Consortium Infrastructure Steering Committee (ISC), members have a voice in the process of selecting projects and the opportunity to guide their development.
-   Gives companies direct access to the R Foundation:
    -   Board members interact with the R Foundation’s representative on the R Consortium Board of Directors.
    -   ISC members:
        -   Work side-by-side with R Foundation members engaged in technical projects,
        -   Participate in regular meetings with R Foundation members.
-   Provides insight and access to accurate and up-to-date knowledge about important developments in the the R Community and the extended R ecosystem.

## How R Consortium membership helps support the R Community

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(gt)
})

df <- data.frame(
  Benefits = c("One seat on the Board of Directors with full voting rights", "One seat on the ISC with full voting rights", "Elect Silver representatives to the Board and ISC (1 Board seat per 3 Silver members, 1 ISC seat for all Silver members)", "Company logo on R Consortium website and collateral", "R Consortium logo on company website", "Membership dues (annually)"),
  Platinum = c("Check", "Check", "None", "Check", "Check", "US$100,000"),
  Silver = c("None", "None", "Check", "Check", "Check", "100+ FTE US $25,000 <100 FTE / non-profits, universities US $10,000"),
  stringsAsFactors = FALSE
)


df <- df |>
  dplyr::mutate(
    Platinum = case_when(Platinum == "Check" ~ "check", Platinum == "None" ~ "xmark",TRUE ~ Platinum )
  ) |>
  dplyr::mutate(
    Silver = case_when(Silver == "Check" ~ "check", Silver == "None" ~ "xmark",TRUE ~ Silver )
  ) 



gt(df) %>%
  fmt_icon(columns = c(Platinum, Silver), rows = c(1:5), fill_color = c("check" = "green", "xmark" = "darkred")) %>%

  cols_label(
    Benefits = "Benefits by member class",
    Platinum = "Platinum",
    Silver = "Silver"
  ) %>%
  tab_options(
    heading.background.color = "lightblue",
    column_labels.background.color = "lightblue",
    column_labels.font.weight = "bold",
    table.font.size = "14px",
    column_labels.font.size = "16px"
    
   
  ) %>%
  cols_align(align="center", columns=c(Platinum, Silver)) %>%
  opt_horizontal_padding(scale = 3)  %>%
  opt_vertical_padding(scale = 2)
  
```


### Joining the R Consortium is easy.

1. Review the Membership Documents.

-   [R Consortium Membership Datasheet](../rc-docs/r_consortium_datasheet.pdf) (PDF)
-   [R Consortium Bylaws](../rc-docs/R-Consortium-Bylaws-7-9-2024.pdf) (PDF)
-   [R Consortium Membership Agreement](../rc-docs/R-Consortium-Membership-Agreement-1157181-v2-Approved-11.20.19.pdf) (PDF)
-   [R Consortium – Certificate of Incorporation](../rc-docs/R-Consortium-Certificate-of-Incorporation.pdf) (PDF)

2. Fill out our online [membership application form](https://join.r-consortium.org/).

3. Remit the annual dues payment that is applicable for your membership level.

4. Begin participating in Events, Discussions, Projects and working Groups.

If you have questions about membership or joining the R Consortium, please contact our [member support desk](https://members.r-consortium.org/) and you will be contacted as soon as possible. Thank you.