---
aliases:
  - call-for-proposals
---

# The 2025 ISC Grant Program

A major goal of the R Consortium is to strengthen and improve the infrastructure supporting the R Ecosystem. We seek to accomplish this by funding projects that will improve both technical infrastructure and social infrastructure.

Technical Infrastructure projects that have be funded include:

- [R-hub](https://r-hub.github.io/rhub/index.html), a centralized tool for checking R packages
- [Testing DBI](https://github.com/rstats-db/DBItest) and improving key open source database backends.
- Improvements in packages such as [mapview](https://github.com/r-spatial/mapview) and [sf](https://github.com/r-spatial/sf)
- Improving Translations in R
- Ongoing infrastructural development for R on Windows and macOS

Social Infrastructure projects include:

- [SatRDays](http://satrdays.org/), bootstrapping a system for local R conferences.
- Data-Driven Discovery and Tracking of R Consortium Activities

The [Infrastructure Steering Committee (ISC)](../about/governance.html) projects should have a focus on technical infrastructure or involve software development to support social infrastructure. Conferences, training sessions, and user groups will be funded through the [RUGS program](../all-projects/rugsprogram.html).

To apply for an ISC grant please continue with the instructions below. To seek funding for a conference, training session or user group please apply through the [RUGS program page](../all-projects/rugsprogram.html).

## Projects the ISC Funds

The ISC is interested in projects that:

- Are likely to have a broad impact on the R community.
- Have a focused scope (a good example is the [Simple Features for R project](https://github.com/r-spatial/sf)). If you have a larger project, consider breaking it up into smaller chunks (a good example of this done is with the [DBI/DBItest project](http://dbi.r-dbi.org/) submission, where multiple proposals came in over time to address the various needs).
- Have a low-to-medium risk with a low-to-medium reward. The ISC tends not fund high-risk, high-reward projects.

While all projects are considered, the ISC generally does not accept projects that:

- Impact only a small part of the R community
- Request conference, workshop, or meetup sponsorship. For these, you should look at our user group program or connect with the marketing committee for larger events.
- Are very exploratory. These are better to be pursued through the [working group program](../all-projects/isc-working-groups.html).

## Submitting a Proposal

Please provide a 2 to 5 page proposal that describes the problem you want to solve. We expect submissions to include these components:

1. **Executive Summary:** This section provides a condensed view of the entire proposal, one page long. It should be a comprehensive high-level overview that captures the essence of the proposal, including its goals, methods, expected outcomes, deliverables, and budget.

2. **Signatories:** This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important. Willingness to accept outside input is also a good marker for project delivery. Include the project team who will deliver the project, contributors who helped with the proposal, and those who were consulted for feedback.

3. **The Problem:** What problem do you want to solve? Why is it a problem? Who does it affect? What will solving the problem enable? This section should include a brief summary of existing work, such as R packages that may be relevant. If you are proposing a change to R itself, you must include a letter of support from a member of [R Core](https://www.r-project.org/contributors.html).

4. **The Proposal:** How are you going to solve the problem? Include the concrete actions you will take and an estimated timeline. What are likely failure modes and how will you recover from them? Address what your proposal is at a high-level, go into detail about the specifics including minimum viable product, architecture, assumptions, and external dependencies.

5. **Project Plan:** Outline the milestones for development including start-up phase, technical delivery with target dates, dissemination strategy, and funding plan. Specify how much funding will be required for each stage as payments will be tied to project milestone completion. Each milestone should specify the work to be done and expected outcomes. Include how you will ensure your work is available to the widest number of people, specify open-source licenses, hosting plans, and publicity strategy including quarterly R Consortium blog content.

6. **Success:** Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery. Define what success looks like, how you will measure it along the way, and describe potential future work that could extend or develop the project further.

The ISC has a limited grant budget, and we want to ensure that funded projects deliver the maximum benefit to the community. Successful proposals show well-defined milestones, with initial work completed to minimize delivery risk, e.g., upfront research and well-defined action plans.

If you would like a template to help you structure your proposal, we encourage you to use one contributed by [Steph Locke](https://github.com/stephlocke) at [https://github.com/RConsortium/isc-proposal](https://github.com/RConsortium/isc-proposal).

We encourage you to seek feedback from the community before formally submitting your proposal. You are welcome to email individual committee members who might be particularly interested in your proposal to get their informal opinion, and you may want to publicize it more widely to get feedback from the broader R community.

## How to Apply

Once you have completed your proposal, create a self-contained PDF and complete [this form](https://forms.gle/o1nhNrdzebQc2DNU6) (requires signing in via a Google Account). When you submit the form, you should see a response page saying “Thank you for your proposal!” Soon thereafter, you will receive an email from forms-receipts-noreply@google.com with all the details of your submission. If you do not receive that email, please be sure to check your spam folder. If you do not see it, reach out to us as soon as possible.

Please note that the R Consortium utilizes a standard agreement for all funded projects selected in an effort to streamline the award process and to fund the greatest amount of projects as possible. The standard agreement is available for review in advance: [Individual Consultant Agreement for R Consortium ISC Projects – 20170622](../rc-docs/Individual-Consultant-Agreement-for-R-Consortium-ISC-Projects-20170622.pdf).

If you have any questions please email proposal@r-consortium.org.

## Proposal Dates for 2025

### First Grant cycle
- March 1, 2025 – Grant Application period opens
- April 1, 2025 – Grant Application period closes, 11:59pm US ET
- May 1, 2025 – All accepted grantees are contacted by the ISC
- June 1, 2025 – Deadline for acceptance of grant and contract. Public notification of grantees occurs shortly thereafter.

### Second Grant cycle
- September 1, 2025 – Grant Application period opens
- October 1, 2025 – Grant Application period close, 11:59pm US ET
- November 1, 2025 – All accepted grantees are contacted by the ISC
- December 1, 2025 – Deadline for acceptance of grant and contract. Public notification of grantees occurs shortly thereafter.

## The Process

All proposals will be read and reviewed by the Chair of the ISC and assigned to a committee member for detailed review. Proposals will be reviewed as a group, and you will be notified of the decision by the dates listed above.

50% of the grant will be paid out when the contract is signed and 50% upon completion.

All accepted projects will be published on the [R Consortium blog](../blog).

We review this process yearly to ensure that the process is as smooth as possible, and to incorporate the knowledge gained from putting it into practice. All decisions to accept or reject proposals will be made by R Consortium in its sole discretion and shall be final.

If you have any questions about the proposals or submission process write to proposal@r-consortium.org.
