---
format: html
page-layout: full
---


# Goal of ISC Grants Program

The goal of the Infrastructure Steering Committee (the ISC) is to support projects that broadly 
help the R community. This might be software development, developing new teaching materials, 
documenting best practices, standardizing APIs or doing research. Currently, the ISC chiefly 
provides financial support for projects proposed by individuals or teams who have the skills 
to carry out the work, but we can also provide administrative support, promotion and some 
collaboration tools for groups who would like to study more ambitious projects.


The ISC generally funds two grant cycles per year. Cumulatively, we have awarded over $750k in 
community development grants over 5 years. 

Interested in strengthening the R community? [Submit a Proposal](callforproposals.qmd). Please 
note, grants from the R Consortium are not adjusted to accommodate for internal institutional overhead.


## Funded Projects

For activities that are well defined and scoped, yet require funding to help bring to fruition, 
the ISC has established a grant fund. Twice yearly, the ISC awards grants for projects such as 
code development, workshops, infrastructure, and other projects to help sustain the R community.

You can learn more about the [in-progress and completed funded projects](funded-projects.qmd). 
If you have a project needing funding, learn more about [the grant funding process](callforproposals.qmd).

## Top Level Projects

For community projects of importance to the R community and needing long-term support by R Consortium, 
the project and ISC can consider the project for long-term status. This gives the project guaranteed 
funding for 3 years, along with a voting seat on the ISC. Projects looking for this status will need 
to justify to the ISC why the project needs long-term funding, as well as submit a 3-year plan and 
budget for consideration. Top level projects get priority access to grant funds available.

Three projects are currently Top Level Projects:

- [DBI](https://r-dbi.org/)
- [R-Ladies](https://rladies.org/)
- [R User Group Support Program (RUGS)](rugsprogram.qmd)

[Previous Top Level Projects](previous-top-level-projects.qmd)