# R User Group Grants

This page describes how to apply for grants to support R user groups.

For any problems or information, please email [operations@r-consortium.org](#)


# 2025 RUGs Program

The RUGs mission is to facilitate the person-to-person exchange of knowledge in small group settings on a global scale. We continue to believe that the most effective way for people to learn from and about each other, and to set and accomplish common goals is to meet face-to-face on a regular basis. Nevertheless, occasional virtual meetings are acceptable. 

RUGs grants are intended to help people form enduring R user group communities. Active user groups may apply for grants once every calendar year. 


These grants do not include support for software development or technical projects. Grants to support the R ecosystem’s technical infrastructure are awarded and administered through the [ISC Grant Program](https://www.r-consortium.org/all-projects/call-for-proposals), which issues a call for proposals two times each year.


### 📌 Find your local R User Group [here](https://www.meetup.com/pro/r-user-groups/)


---


### Duration of the 2025 RUGs Program

The 2025 RUGs Program will open on March 1, 2025, and close at midnight PST on September 30, 2025. We reserve the right to close the grant window earlier than anticipated based on the number of applications. 


### How to apply for a RUGs Program Grant

To apply for a grant [fill out this form](https://forms.gle/gJMZuq8KxmzrCnuTA). 

 

### Requirements

To be eligible for a RUGs grant, a user group must:



1. Group Organizer must have at least five people in the R User Group
2. Have R as a primary focus
3. Adhere to the [Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/?__hstc=98577409.44d7f16716270a3b9b81de6d864e02dc.1720553161514.1721159359293.1721164323976.8&__hssc=98577409.4.1721164323976&__hsfp=1019891917) published on the R Consortium website
4. Agree to participate in the RUGs meetup.com Pro program and use their meetup.com site to announce and track meetings
5. Acknowledge the R Consortium as a sponsor and display the R Consortium logo on the group’s website
6. Agree to write at least two blog posts per year about their group’s activities for possible publication on the R Consortium Blog
7. Comply with the instructions by completing a W9 Form (US-based groups only) or Wire Transfer form (Groups based outside of the US)
8. Agree to the above in a grant agreement via DocuSign


### Structure

R user groups grants under the RUGs 2025 program come in two parts:



1. R user groups that are not already participating in the RUGs meetup.com Pro account will be enrolled into this program. The R Consortium will pay the group’s meetup.com fees for twelve months after acceptance into the program. Thereafter, the R Consortium will continue to pay meetup.com dues for participating groups as long as the groups comply with the requirements above, remain active, continue to meet at least once every three months, and use meetup.com to schedule and announce meetings. User group organizers do not need to re-apply for meetup.com Pro account participation if the group’s meetup.com account remains active.
2. Cash grants typically vary between $500 and $1,250 and depend on group size and special needs.


# General Requirements



1. Must agree to write 2 blog posts a year
2. Post photos of their meetings onto Meetup.com as appropriate
3. Upload available material to the [R Consortium GitHub Repository](https://github.com/RConsortium/rugs-materials)


# RUGs Grant Amounts and Groups’ Responsibilities 

Brand new R User Group



* The group receives a grant of $500 and membership in Meetup pro
* The group must show 5 people committed to the group
* R Consortium will provide the blog link and best practice guide
* The group must agree to write two blog posts per year

To get a grant of up to $750, all of the above plus:



* The group must meet at least 1 time every 3 months
* The group must have more than 25 people at the meeting
* The group must have photos of the meeting 
* The group must show R Consortium Sponsorship

To get a grant of up to $1,250, all of the above plus:



* The group must meet at least twice every 3 months
* The group must have more than 50 people at the meeting
* The group should provide [presentations available for others](https://github.com/RConsortium/rugs-materials) (The R Consortium will host on [GitHub](https://github.com/RConsortium/rugs-materials))


### Notes



1. R-Ladies maintains a separate meetup.com Pro account. R-Ladies groups must apply directly to R-Ladies for acceptance into their program. They will not be automatically entered into the RUGs meetup.com Pro account.
2. The R Consortium maintains the right to terminate the RUG’s Pro program at any time. Additionally, The R Consortium has the right to terminate a group’s participation in the meetup.com Pro program if they do not comply with the requirements specified in the Code of Conduct.
3. If you are seeking information for a conference, please email your prospectus to [marketing@r-consortium.org](#).



### Also, note that any training materials developed with R Consortium funds must be made publicly available with an open source license.


### How to Apply for a RUGs Grant

Apply for a grant by filling out [this form](https://forms.gle/8MRf5uw3xQUz4pXx9).
